-- ─────────────────────────────────────────────────────────────────────────
-- SEED: companies  (GERADO AUTOMATICAMENTE por scripts/generate-seed.mjs)
-- NÃO edite à mão — rode `npm run seed:gen` para regenerar.
--
-- Total: 168 empresas  |  161 ativas  |  7 inativas (SAIU)
-- Fonte: array COMPANIES do controle_apuracao_online.html
-- cnpj / regime / municipio / uf ficam NULL (complementar via XLSX).
-- ─────────────────────────────────────────────────────────────────────────

insert into public.companies
  (cod, empresa, tipo, grupo, iss, icms, sf, sc, resp_padrao, ativo)
values
  ('8', 'AM Assessoria e Consultoria Tributária Ltda', 'Serviços', 'GRUPO 01', true, false, false, true, 'MARIANNA', true),
  ('10', 'Jomap Rio Bombas Injetoras e Peças Ltda', 'Comércio / Serviços', 'GRUPO 06', true, true, true, true, 'MARIA EDUARDA', true),
  ('17', 'Zilma de Oliveira Gonçalves Mercearia', 'Comércio', null, false, true, true, true, 'MARIA EDUARDA', true),
  ('23', 'Simples Saúde Serviços Médicos Ltda - Matriz', 'Serviços', 'GRUPO 17', true, false, false, true, 'MARIANNA', true),
  ('34', 'G.A Bombas Injetoras e Peças Ltda', 'Comércio / Serviços', 'GRUPO 06', true, true, true, true, 'MARIA EDUARDA', true),
  ('37', 'Guaitai Comércio de Roupas Ltda', 'Comércio', 'GRUPO 03', false, true, true, true, 'MARIA EDUARDA', true),
  ('54', 'Líder da Curicica Drogaria e Perfumaria Ltda', 'Comércio', 'GRUPO 24', false, true, true, true, 'MARIANNA', true),
  ('55', 'Hortifruti e Mercearia Curty Ltda', 'Comércio', 'GRUPO 24', false, true, true, true, 'MARIANNA', true),
  ('58', 'Juanil Transportes Rodoviários Ltda', 'Serviços', null, true, false, false, true, 'MARIA EDUARDA', true),
  ('60', 'Centro Médico de Mesquita Medicina Ltda', 'Serviços', 'GRUPO 06', true, false, false, true, 'MARIA EDUARDA', true),
  ('62', 'Nova Era Prime Corretora de Seguros de Vida, CAP e PP Ltda', 'Serviços', 'GRUPO 06', true, false, false, true, 'MARIA EDUARDA', true),
  ('63', 'JCC Corretora de Seguros Ltda', 'Serviços', null, true, false, false, true, 'MARIANNA', true),
  ('65', 'Belford Roxo Eletronics Express Ltda', 'Comércio / Serviços', 'GRUPO 04', true, true, true, true, 'MARIA EDUARDA', true),
  ('68', 'Costa Verde Comércio de Peças Motores e Serviços  Filial Mangaratiba', 'Comércio / Serviços', 'GRUPO 15', true, true, true, true, 'MARIANNA', true),
  ('69', 'Costa Verde Comércio de Peças Motores e Serviços  Matriz', 'Comércio / Serviços', 'GRUPO 15', true, true, true, true, 'MARIANNA', true),
  ('70', 'Costa Verde Motores Paraty Ltda - vai ser cancelada', 'Comércio / Serviços', 'GRUPO 15', true, true, true, true, 'MARIANNA', true),
  ('72', 'Central Assistência de Eletrônicos Ltda', 'Comércio / Serviços', 'GRUPO 04', true, true, true, true, 'MARIA EDUARDA', true),
  ('73', 'Linkcell Celulares Ltda (S/Certificado)', 'Serviços', 'GRUPO 04', true, false, false, true, 'MARIA EDUARDA', true),
  ('74', 'Madureira Reparação, Manut e Com de Equip de Com Ltda', 'Comércio / Serviços', 'GRUPO 04', true, true, true, true, 'MARIA EDUARDA', true),
  ('75', 'Nova Iguaçu Eletronics Expressa Ltda', 'Comércio / Serviços', 'GRUPO 04', true, true, true, true, 'MARIA EDUARDA', true),
  ('76', 'Paulo Pires Eletrônica Ltda (S/Certificado)', 'Comércio / Serviços', 'GRUPO 04', true, true, true, true, 'MARIA EDUARDA', true),
  ('82', 'Maciel Serv e Com de Peças e Acessórios para Veículos Ltda', 'Comércio / Serviços', null, true, true, true, true, 'MARIANNA', true),
  ('83', 'Auto Mecânica JG Ltda', 'Comércio / Serviços', 'GRUPO 10', true, true, true, true, 'MARIA EDUARDA', true),
  ('84', 'Atacadista Dois Irmãos Comércio Ltda', 'Comércio', null, false, true, true, true, 'MARIANNA', true),
  ('85', 'Multiplus R D Tecnologia e Serviços Automotivos Ltda', 'Comércio / Serviços', null, true, true, true, true, 'MARIANNA', true),
  ('86', 'P Olimpio da Silva Peças e Motos Ltda', 'Comércio', null, false, true, true, true, 'MARIA EDUARDA', true),
  ('87', 'Lorena Del Puppo Luz Serviços Médicos Ltda -  Matriz', 'Serviços', 'GRUPO 16', true, false, false, true, 'MARIA EDUARDA', true),
  ('89', 'TMC Serviços e Tecnologia Ltda - André', 'Serviços', null, true, false, false, true, 'MARIANNA', true),
  ('90', 'AM Contabilidade e Auditoria Ltda', 'Serviços', 'GRUPO 01', true, false, false, true, 'MARIANNA', true),
  ('91', 'JF Auto Diesel Mecânica Automotiva Ltda', 'Comércio / Serviços', null, true, true, true, true, 'MARIA EDUARDA', true),
  ('94', 'AC Comércio de Roupas e Acessórios Ltda', 'Comércio', 'GRUPO 03', false, true, true, true, 'MARIA EDUARDA', true),
  ('96', 'HSR Serviços Automotivos Ltda', 'Serviços', 'GRUPO 10', true, false, false, true, 'MARIA EDUARDA', true),
  ('99', 'Villa & Blue 2023 Restaurante Ltda', 'Comércio', null, false, true, true, true, 'MARIANNA', true),
  ('100', 'AGM H. PRODUTOS ALIMENTICIOS', 'Comércio', null, false, false, false, false, 'MARIANNA', true),
  ('103', 'C T V C Eletronica Ltda', 'Comércio / Serviços', 'GRUPO 04', true, true, true, true, 'MARIA EDUARDA', true),
  ('104', 'Posto de Molas Audax Comércio de Peças Ltda', 'Comércio / Serviços', null, true, true, true, true, 'MARIA EDUARDA', true),
  ('105', 'Nova União Irmãos Auto Center Ltda', 'Comércio / Serviços', null, true, true, true, true, 'MARIA EDUARDA', true),
  ('108', 'CARDOSO MONTAGNANI', 'Comércio / Serviços', null, false, false, false, false, 'MARIANNA', true),
  ('110', 'Simples Saúde Serviços Médicos Ltda - Filial', 'Serviços', 'GRUPO 17', true, false, false, true, 'MARIANNA', true),
  ('111', 'Lorena Del Puppo Luz Serviços Médicos Ltda -  Filial', 'Serviços', 'GRUPO 16', true, false, false, true, 'MARIA EDUARDA', true),
  ('114', 'BIGNETH', 'Comércio / Serviços', null, false, false, false, false, 'MARIA EDUARDA', true),
  ('119', 'Fênix RJ Com e Serv de Prod Industriais e Automotivos Ltda', 'Comércio / Serviços', null, true, true, true, true, 'MARIA EDUARDA', true),
  ('123', 'Rinelli Carrico Rianelli de Lima', 'Comércio / Serviços', null, true, true, true, true, 'MARIANNA', true),
  ('125', 'R2 Embalagens Comércio e Serviços Ltda', 'Comércio / Serviços', 'GRUPO 07', true, true, true, true, 'MARIA EDUARDA', true),
  ('126', 'R1 Comércio e Serviços Ltda', 'Comércio / Serviços', 'GRUPO 07', true, true, true, true, 'MARIA EDUARDA', true),
  ('127', 'Maricá Comércio e Serviços de Embalagens Ltda', 'Comércio / Serviços', 'GRUPO 07', true, true, true, true, 'MARIA EDUARDA', true),
  ('128', 'Baiaco Materiais de Construção Ltda', 'Comércio', null, false, true, true, true, 'MARIA EDUARDA', true),
  ('130', 'Espaço de Lazer Tucano Ltda', 'Comércio / Serviços', 'GRUPO 27', true, true, true, true, 'MARIANNA', true),
  ('131', 'Barras Vans Car Ltda', 'Comércio / Serviços', 'GRUPO 14', true, true, true, true, 'MARIA EDUARDA', false),
  ('132', 'Ephraim Bikes Elétricas Ltda - Quitungo', 'Comércio / Serviços', 'GRUPO 14', true, true, true, true, 'MARIA EDUARDA', false),
  ('133', 'Alex Alonso Gil Aluguel de Equipamentos e Serv. Engenharia', 'Serviços', null, true, false, false, true, 'MARIANNA', true),
  ('135', 'AJSP Empresa de Transp e Agencia de Turismo Ltda - 11', 'Comércio / Serviços', 'GRUPO 13', true, true, true, true, 'MARIANNA', false),
  ('136', 'AJSP Empresa de Transp e Agencia de Turismo Ltda - 22', 'Comércio / Serviços', 'GRUPO 13', true, true, true, true, 'MARIANNA', false),
  ('137', 'Transmartins Transportes e Turismo Ltda', 'Serviços', 'GRUPO 26', true, false, false, true, 'MARIA EDUARDA', true),
  ('138', 'Bmar Transportes e Logisticas Ltda - TC Transportes', 'Serviços', 'GRUPO 26', true, false, false, true, 'MARIA EDUARDA', true),
  ('141', 'Andrea D.S.A', 'Comércio / Serviços', null, false, false, false, false, 'MARIANNA', true),
  ('144', 'Studio Wolver Barber Designer Ltda', 'Serviços', 'GRUPO 14', true, false, false, true, 'MARIA EDUARDA', false),
  ('145', 'Axiste Comercio de Produtos Medicos Hospitalares', 'Comércio', 'GRUPO 25', false, true, true, true, 'MARIANNA', true),
  ('146', 'Eco Medice - Distribuidora de Produtos Medicos Hospitalares', 'Comércio', 'GRUPO 25', false, true, true, true, 'MARIANNA', true),
  ('150', 'Cinticedi Medicina Nuclear Ltda', 'Serviços', 'GRUPO 19', true, false, false, true, 'MARIANNA', true),
  ('151', 'Cinticedi Medicina Nuclear Ltda', 'Serviços', 'GRUPO 19', true, false, false, true, 'MARIANNA', true),
  ('152', 'Cinticedi Medicina Nuclear Ltda', 'Serviços', 'GRUPO 19', true, false, false, true, 'MARIANNA', true),
  ('153', 'Cinticedi Medicina Nuclear Ltda', 'Serviços', 'GRUPO 19', true, false, false, true, 'MARIANNA', true),
  ('154', 'As Poderosas by Leticia Figueiredo Sociedade Empresarial Ltda', 'Comércio', 'GRUPO 12', false, true, true, true, 'MARIA EDUARDA', true),
  ('155', 'Hapia Veiculos Ltda', 'Comércio / Serviços', 'GRUPO 07', true, true, true, true, 'MARIA EDUARDA', true),
  ('156', 'Jacklux Quimica Ltda', 'Comércio / Serviços', null, true, true, true, true, 'MARIA EDUARDA', true),
  ('157', 'Promise Veiculos Ltda', 'Comércio / Serviços', 'GRUPO 07', true, true, true, true, 'MARIA EDUARDA', true),
  ('160', 'Ephraim Motos Elétricas Ltda', 'Comércio / Serviços', 'GRUPO 14', true, true, true, true, 'MARIA EDUARDA', false),
  ('164', 'TopFire - Escola de Emergência Ltda', 'Serviços', 'GRUPO 08', true, false, false, true, 'MARIA EDUARDA', true),
  ('165', 'Efraym 8 Peças Diesel e Acessórios Ltda', 'Comércio / Serviços', null, true, true, true, true, 'MARIANNA', true),
  ('169', 'Ephraim Bikes Elétricas Ltda - Vila da Penha', 'Comércio / Serviços', 'GRUPO 14', true, true, true, true, 'MARIA EDUARDA', false),
  ('170', 'HEAD INFORMATICA MULTIMARCAS LTDA', 'Comércio / Serviços', null, false, false, false, false, 'MARIANNA', true),
  ('171', 'R. S. Ribeiro Serviços e Tecnologia Automotiva Ltda', 'Serviços', null, true, false, false, true, 'MARIA EDUARDA', true),
  ('172', 'Medicine With BeautyServiços Ltda', 'Comércio / Serviços', 'GRUPO 09', true, true, true, true, 'MARIANNA', true),
  ('173', 'BV Arquitetura e Interiores Ltda', 'Serviços', null, true, false, false, true, 'MARIA EDUARDA', true),
  ('174', 'Fire Segmento Técnico Ltda', 'Serviços', 'GRUPO 08', true, false, false, true, 'MARIA EDUARDA', true),
  ('175', 'La Vie Café Ltda - ME', 'Comércio', 'GRUPO 09', false, true, true, true, 'MARIANNA', true),
  ('178', 'Clinica MWB Ltda', 'Serviços', 'GRUPO 09', true, false, false, true, 'MARIANNA', true),
  ('179', 'Costa Verde Comércio de Peças Motores e Serviços  Filial Paraty', 'Comércio / Serviços', 'GRUPO 15', true, true, true, true, 'MARIANNA', true),
  ('180', 'Costa Verde Comércio de Veículos Ltda', 'Comércio / Serviços', 'GRUPO 15', true, true, true, true, 'MARIANNA', true),
  ('181', 'Guedes e Gonçalves Comércio e Representações Ltda', 'Comércio / Serviços', 'GRUPO 23', true, true, true, true, 'MARIANNA', true),
  ('182', 'GVBV Comércio e Representações Ltda', 'Comércio', 'GRUPO 23', false, true, true, true, 'MARIANNA', true),
  ('183', 'Instituto de Medicina Comércio com Beleza Ltda', 'Comércio / Serviços', 'GRUPO 09', true, true, true, true, 'MARIANNA', true),
  ('184', 'TR Solution Terceirização de Serviços Ltda', 'Serviços', null, true, false, false, true, 'MARIANNA', true),
  ('185', 'Transtucano de Iguacu 2008 Ltda', 'Comércio / Serviços', 'GRUPO 27', true, true, true, true, 'MARIANNA', true),
  ('186', 'Vibe Embalagens Comércio de Descartáveis Ltda', 'Comércio', 'GRUPO 23', false, true, true, true, 'MARIANNA', true),
  ('187', 'Anestesiologia Albuquerque Ltda', 'Serviços', null, true, false, false, true, 'MARIA EDUARDA', true),
  ('188', 'Dynamis Soluções em Eletroeletrônicos Ltda', 'Comércio / Serviços', 'GRUPO 05', true, true, true, true, 'MARIANNA', true),
  ('189', 'Dynamis Soluções em Eletroeletrônicos Ltda', 'Comércio / Serviços', 'GRUPO 05', true, true, true, true, 'MARIANNA', true),
  ('190', 'Dynamis Soluções em Eletroeletrônicos Ltda', 'Comércio / Serviços', 'GRUPO 05', true, true, true, true, 'MARIANNA', true),
  ('191', 'Dynamis Soluções em Eletroeletrônicos Ltda', 'Comércio / Serviços', 'GRUPO 05', true, true, true, true, 'MARIANNA', true),
  ('192', 'Dynamis Soluções em Eletroeletrônicos Ltda', 'Comércio / Serviços', 'GRUPO 05', true, true, true, true, 'MARIANNA', true),
  ('193', 'Dynamis Soluções em Eletroeletrônicos Ltda', 'Comércio / Serviços', 'GRUPO 05', true, true, true, true, 'MARIANNA', true),
  ('194', 'GMB Comercio de Artigos Eletrônicos Ltda', 'Comércio / Serviços', 'GRUPO 05', true, true, true, true, 'MARIANNA', true),
  ('195', 'GMB Comercio de Artigos Eletrônicos Ltda', 'Comércio / Serviços', 'GRUPO 05', true, true, true, true, 'MARIANNA', true),
  ('196', 'GMB Comercio de Artigos Eletrônicos Ltda', 'Comércio / Serviços', 'GRUPO 05', true, true, true, true, 'MARIANNA', true),
  ('197', 'GMB Comercio de Artigos Eletrônicos Ltda', 'Comércio / Serviços', 'GRUPO 05', true, true, true, true, 'MARIANNA', true),
  ('198', 'Facility 01 Multimarcas Ltda', 'Comércio / Serviços', 'GRUPO 11', true, true, true, true, 'MARIA EDUARDA', true),
  ('199', 'Horus Premium', 'Comércio', 'GRUPO 11', false, true, true, true, 'MARIA EDUARDA', true),
  ('200', 'Sentinella Multimarcas Ltda', 'Comércio', 'GRUPO 11', false, true, true, true, 'MARIA EDUARDA', true),
  ('201', 'ROSELI CLEIDE OLIVEIRA LTDA', 'Comércio', null, false, false, false, false, 'MARIANNA', true),
  ('202', 'Studio Leticia Figueiredo Instituto de Beleza Ltda', 'Comércio / Serviços', 'GRUPO 12', true, true, true, true, 'MARIA EDUARDA', true),
  ('203', 'Adriana Ribeiro Figueiredo', 'Serviços', null, true, false, false, true, 'MARIANNA', true),
  ('204', 'Ivisa Assessoria Ltda', 'Serviços', null, true, false, false, true, 'MARIA EDUARDA', true),
  ('205', 'ECP - ENVIRON CONSULTORIA E PROJETOS LTDA', 'Comércio / Serviços', 'GRUPO 18', false, false, false, false, 'MARIA EDUARDA', true),
  ('207', 'TAP TECH LTDA', 'Comércio / Serviços', 'GRUPO 29', false, false, false, false, 'MARIA EDUARDA', true),
  ('208', 'SMART SERVICE ASSISTENCIA E ACESSORIOS LTDA', 'Comércio / Serviços', 'GRUPO 28', false, false, false, false, 'MARIA EDUARDA', true),
  ('210', 'RAJS TRADE MARKETING', 'Comércio / Serviços', null, false, false, false, false, 'MARIANNA', true),
  ('211', 'P&C SOLUÇÕES EMPRESARIAIS', 'Comércio / Serviços', 'GRUPO 21', false, false, false, false, 'MARIANNA', true),
  ('213', 'Cezar do Ar Instalação Automotiva Ltda', 'Comércio / Serviços', 'GRUPO 22', false, false, false, true, 'MARIANNA', true),
  ('214', 'Auto Elétrica e Refrigeração Boa Amizade Ltda', 'Comércio / Serviços', 'GRUPO 22', true, true, true, true, 'MARIANNA', true),
  ('215', 'FB Participações Imobiliárias Ltda', 'Comércio / Serviços', null, true, true, true, true, 'MARIA EDUARDA', true),
  ('216', 'LEFEL HOLDING E PARTICIPAÇÕES LTDA', 'Comércio / Serviços', 'GRUPO 18', false, false, false, false, 'MARIA EDUARDA', true),
  ('217', 'ECP - AGRO CONSULTORIA E PROJETOS LTDA', 'Comércio / Serviços', 'GRUPO 18', false, false, false, false, 'MARIA EDUARDA', true),
  ('218', 'GRUPO GARRA MANUTENCOES E SERVICOS LTDA', 'Comércio / Serviços', 'GRUPO 20', false, false, false, false, 'MARIANNA', true),
  ('219', 'GRUPO GARRA 2020 SERVICOS LTDA', 'Comércio / Serviços', 'GRUPO 20', false, false, false, false, 'MARIANNA', true),
  ('220', 'GARRA 2023 SERVIÇOES INTELIGENTES  LTDA', 'Comércio / Serviços', 'GRUPO 20', false, false, false, false, 'MARIANNA', true),
  ('221', 'GARRA 2024 SERVICOS DE MANUTENCOES LTDA', 'Comércio / Serviços', 'GRUPO 20', false, false, false, false, 'MARIANNA', true),
  ('222', 'GARRA 2025 SERVICO INTELIGENTE LTDA', 'Comércio / Serviços', 'GRUPO 20', false, false, false, false, 'MARIANNA', true),
  ('223', 'GARRA 2026 MANUTENCOES E SERVICOS LTDA', 'Comércio / Serviços', 'GRUPO 20', false, false, false, false, 'MARIANNA', true),
  ('224', 'P&C SOLUÇÕES EMPRESARIAIS', 'Comércio / Serviços', 'GRUPO 21', false, false, false, false, 'MARIANNA', true),
  ('225', 'AM Importadora E exportadora Ltda', 'Comércio', 'GRUPO 01', false, false, false, false, 'MARIANNA', true),
  ('226', 'Carmo Diniz Serviço e Comércio Ltda', 'Comércio / Serviços', null, true, true, true, true, 'MARIA EDUARDA', true),
  ('227', 'P&C SOLUÇÕES EMPRESARIAIS', 'Comércio / Serviços', 'GRUPO 21', false, false, false, false, 'MARIANNA', true),
  ('229', 'Leve Pocket Ltda', 'Comércio / Serviços', null, false, false, false, true, 'MARIANNA', true),
  ('230', 'FAZALL SERVIÇOS LTDA', 'Comércio / Serviços', null, false, false, false, false, 'MARIA EDUARDA', true),
  ('231', 'RIO VEDAS', 'Comércio / Serviços', null, false, false, false, false, 'MARIANNA', true),
  ('232', 'FAVORITA', 'Comércio / Serviços', null, false, false, false, false, 'MARIA EDUARDA', true),
  ('233', 'RBRX EMPREENDIMENTOS IMOBILIARIOS LTDA', 'Comércio / Serviços', null, false, false, false, false, 'MARIANNA', true),
  ('234', 'FORT RODAS DISTRIBUIDORA E COMERCIO LTDA', 'Comércio / Serviços', null, false, false, false, false, 'MARIA EDUARDA', true),
  ('235', 'Adalex Construções Ltda', 'Comércio / Serviços', null, false, false, false, false, 'MARIA EDUARDA', true),
  ('236', 'ALFA PORT', 'Serviços', null, false, false, false, false, 'MARIA EDUARDA', true),
  ('237', 'Anju Prieto', 'Comércio', null, false, false, false, false, 'MARIA EDUARDA', true),
  ('239', 'R S SPORT BIKE LTDA', 'Comércio', null, false, false, false, false, 'MARIA EDUARDA', true),
  ('240', 'ITAGUAI DIESEL COMERCIO DE PEÇAS PARA VEICULOS LTDA', 'Comércio', null, false, false, false, false, 'MARIA EDUARDA', true),
  ('241', 'CORAZA ATOMOTIVA LTDA', 'Serviços', null, false, false, false, false, 'MARIA EDUARDA', true),
  ('242', 'DROGARIA TIJUQUINHA LTDA', 'Comércio', null, false, false, false, false, 'MARIANNA', true),
  ('243', 'FARMACIA GAFEDIMA LTDA', 'Comércio', null, false, false, false, false, 'MARIANNA', true),
  ('244', 'BRAVO 1 SOLUCOES PATRIMONIAIS LTDA', 'Serviços', null, false, false, false, false, 'MARIA EDUARDA', true),
  ('245', 'SMART SERVICE ASSISTENCIA E ACESSORIOS LTDA', 'Comércio', 'GRUPO 28', false, false, false, false, 'MARIA EDUARDA', true),
  ('246', 'SMART SERVICE ASSISTENCIA E ACESSORIOS LTDA', 'Comércio', 'GRUPO 28', false, false, false, false, 'MARIA EDUARDA', true),
  ('247', 'SMART SERVICE ASSISTENCIA E ACESSORIOS LTDA', 'Comércio', 'GRUPO 28', false, false, false, false, 'MARIA EDUARDA', true),
  ('248', 'P&C SOLUÇÕES EMPRESARIAIS', 'Serviços', 'GRUPO 21', false, false, false, false, 'MARIANNA', true),
  ('249', 'TAP TECH LTDA', 'Comércio', 'GRUPO 29', false, false, false, false, 'MARIA EDUARDA', true),
  ('250', 'TAP TECH LTDA', 'Comércio', 'GRUPO 29', false, false, false, false, 'MARIA EDUARDA', true),
  ('251', 'TAP TECH LTDA', 'Comércio', 'GRUPO 29', false, false, false, false, 'MARIA EDUARDA', true),
  ('252', 'CONECTTA ACESSORIOS E SOLUCOES LTDA', 'Comércio', 'GRUPO 30', false, false, false, false, 'MARIA EDUARDA', true),
  ('253', 'CONECTTA ACESSORIOS E SOLUCOES LTDA', 'Comércio', 'GRUPO 30', false, false, false, false, 'MARIA EDUARDA', true),
  ('254', 'CONECTTA ACESSORIOS E SOLUCOES LTDA', 'Comércio', 'GRUPO 30', false, false, false, false, 'MARIA EDUARDA', true),
  ('255', 'SOLUTECH ARTIGOS E ACESSÓRIOS ELETRÔNICOS LTDA', 'Comércio', 'GRUPO 32', false, false, false, false, 'MARIANNA', true),
  ('256', 'SOLUTECH ARTIGOS E ACESSÓRIOS ELETRÔNICOS LTDA', 'Comércio', 'GRUPO 32', false, false, false, false, 'MARIANNA', true),
  ('257', 'SOLUTECH ARTIGOS E ACESSÓRIOS ELETRÔNICOS LTDA', 'Comércio', 'GRUPO 32', false, false, false, false, 'MARIANNA', true),
  ('258', 'SOLUTECH ARTIGOS E ACESSÓRIOS ELETRÔNICOS LTDA', 'Comércio', 'GRUPO 32', false, false, false, false, 'MARIANNA', true),
  ('259', 'THDG. COM TECHNOLOGY E COMERCIO LTDA EPP', 'Comércio', 'GRUPO 33', false, false, false, false, 'MARIA EDUARDA', true),
  ('260', 'THDG. COM TECHNOLOGY E COMERCIO LTDA EPP', 'Comércio', 'GRUPO 33', false, false, false, false, 'MARIA EDUARDA', true),
  ('261', 'THDG. COM TECHNOLOGY E COMERCIO LTDA EPP', 'Comércio', 'GRUPO 33', false, false, false, false, 'MARIA EDUARDA', true),
  ('262', 'THDG. COM TECHNOLOGY E COMERCIO LTDA EPP', 'Comércio', 'GRUPO 33', false, false, false, false, 'MARIA EDUARDA', true),
  ('263', 'THDG. COM TECHNOLOGY E COMERCIO LTDA EPP', 'Comércio', 'GRUPO 33', false, false, false, false, 'MARIA EDUARDA', true),
  ('264', 'THDG. COM TECHNOLOGY E COMERCIO LTDA EPP', 'Comércio', 'GRUPO 33', false, false, false, false, 'MARIA EDUARDA', true),
  ('265', 'THDG. COM TECHNOLOGY E COMERCIO LTDA EPP', 'Comércio', 'GRUPO 33', false, false, false, false, 'MARIA EDUARDA', true),
  ('266', 'THDG. COM TECHNOLOGY E COMERCIO LTDA EPP', 'Comércio', 'GRUPO 33', false, false, false, false, 'MARIA EDUARDA', true),
  ('267', 'THDG. COM TECHNOLOGY E COMERCIO LTDA EPP', 'Comércio', 'GRUPO 33', false, false, false, false, 'MARIA EDUARDA', true),
  ('268', 'C&S CONSULTORIA E TECNOLOGIA LTDA', 'Serviços', null, false, false, false, false, 'MARIA EDUARDA', true),
  ('269', 'G20 IMPORTAÇÃO MAGAZINE LTDA', 'Comércio', 'GRUPO 34', false, false, false, false, 'MARIANNA', true),
  ('270', 'G20 IMPORTAÇÃO & COMÉRCIO LTDA', 'Comércio', 'GRUPO 34', false, false, false, false, 'MARIANNA', true),
  ('271', 'G20 COMÉRCIO VAREJISTA E ATACADISTA LTDA', 'Comércio', 'GRUPO 34', false, false, false, false, 'MARIANNA', true),
  ('272', 'G10 MAGAZINE IMPORTAÇÃO E COMÉRCIO LTDA', 'Comércio', 'GRUPO 34', false, false, false, false, 'MARIANNA', true),
  ('273', 'GR IMPORTADOS COMERCIO ARTIGOS ARMARINHO LTDA', 'Comércio', 'GRUPO 34', false, false, false, false, 'MARIANNA', true)
on conflict (cod) do update set
  empresa     = excluded.empresa,
  tipo        = excluded.tipo,
  grupo       = excluded.grupo,
  iss         = excluded.iss,
  icms        = excluded.icms,
  sf          = excluded.sf,
  sc          = excluded.sc,
  resp_padrao = excluded.resp_padrao,
  ativo       = excluded.ativo;
